services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: db_password
      MYSQL_DATABASE: nestdb
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - '3308:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pdb_password"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  dbdata: